Repository boost-starai/BoostSRL, pull requests merged in 2018-03, with the labels that each got.

#10 setRandomWalkFlag
  src/edu/wisc/cs/will/FOPC/PredicateName.java
  src/edu/wisc/cs/will/FOPC_MLN_ILP_Parser/FileParser.java
Labels: enhancement

#9 Community Standards
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/WikiHowTo.md
Labels: documentation

#8 Maven build. BoostSRL README overhaul. Contribution guidelines. Reorganization.
  .github/CONTRIBUTING.md
  .gitignore
  README.md
  docs/README.md
  docs/WILLManual/README.txt
  docs/WILLManual/User_Manual_of_WILL_0.1.pdf
  docs/WILLManual/algorithm.sty
  docs/WILLManual/algorithmic.sty
  docs/WILLManual/figs/new_run_configuration.png
  docs/WILLManual/figs/open_run_configurations.png
  docs/WILLManual/figs/run_configuration_arguments.png
  docs/WILLManual/figs/run_configuration_ilpmain.png
  docs/WILLManual/will-manual.aux
  docs/WILLManual/will-manual.bbl
  docs/WILLManual/will-manual.blg
  docs/WILLManual/will-manual.dvi
  docs/WILLManual/will-manual.log
  docs/WILLManual/will-manual.out
  docs/WILLManual/will-manual.pdf
  docs/WILLManual/will-manual.tcp
  docs/WILLManual/will-manual.tex
  docs/WILLManual/will-manual.toc
  docs/WILLManual/will-manual.tps
  docs/WILLManual/will.bib
  docs/WILLManual/will_definitions.tex
  docs/WILLManual/willmanualproject/willmanualproject.tcp
  docs/WILLManual/willmanualproject/willmanualproject.tex
  docs/WILLManual/willmanualproject/willmanualproject.tps
  pom.xml
Labels: documentation, enhancement
